name: Aggiorna Interpelli ogni 15 minuti
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
jobs:
  run-worker-once:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12.0" }
      - name: Install deps
        working-directory: interpelli-automatico-max-personal/worker
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run worker
        working-directory: interpelli-automatico-max-personal/worker
        run: python run.py
